services:
  go-graphql-messageboard:
    build: .
    container_name: go-graphql-messageboard
    networks:
      - app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=messageboard-db-user
      - DB_PASSWORD=messageboard-db-password
      - DB_NAME=messageboardDB
  postgres:
    image: postgres:alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    networks:
      - app
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_seed.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}" ]
      interval: 5s
      start_period: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres-db:

networks:
  app: