// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type AddNewCommentInput struct {
	PostID string `json:"postId"`
	Text   string `json:"text"`
}

type AddNewPostInput struct {
	Text string `json:"text"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
